/*
 * ultrasonic_Program.c
 *
 *  Created on: Nov 11, 2023
 *      Author: DeLL
 */

#include "../../../MCAL/DIO/HEADER/DIO_PROTO_TYPES.h" /*To setup the direction for Trigger pin*/
/*To call functions from ICU driver*/
#include "../../../MCAL/ICU/HEADER/ICU_PROTO_TYPES.h"
#include <util/delay.h> /*To give a small delay in the trigger function*/

#include "../HEADER/ultrasonic_CONFIG.h"
#include "../HEADER/ultrasonic_PROTO_TYPES.h"
#include "../HEADER/ultrasonic_REGs.h"



/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

/* Global variable to count the number of edges being detected by the ICU*/
uint8 g_edgeCount = 0;

/*Global variable to calculate the High Time of the signal which is the time
 *required to calculate the distance*/
uint16 g_timeHigh = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description: Function to initialize the Ultrasonic Driver.
 * 	1. Initialize the ICU driver as required.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through
 * 	the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/*Configuration structure for ICU driver with initial conditions*/
	Icu_ConfigType Icu_Config = {F_CPU_8, RISING};

	/*Initialize the ICU driver*/
	Icu_init(&Icu_Config);

	/*Setup the ICU call back function pointer to the ICU Driver*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/*Setup the direction for the trigger pin as output*/
	DIO_SET_PIN_DIREC(Trigger_PORT_ID, Trigger_PIN_ID, OUTPUT);
}

/*
 * Description:
 * Send the Trigger Pulse to the Ultrasonic using the GPIO Driver.
 */
void Ultrasonic_Trigger(void)
{
	/*Send the pulse by writing '1' to the trigger's pin*/
	DIO_SET_PIN_VALUE(Trigger_PORT_ID, Trigger_PIN_ID, STD_HIGH);

	/*Small delay between writing and clearing the trigger's pin*/
	_delay_us(10);

	/*Clear the trigger's pin by writing '0' after sending the pulse*/
	DIO_SET_PIN_VALUE(Trigger_PORT_ID, Trigger_PIN_ID, STD_LOW);
}

/*
 * Description:
 * 1. Send the Trigger Pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance_cm;

	/*Send the Trigger Pulse*/
	Ultrasonic_Trigger();

	/*Start the measurements by the ICU*/

	/*Calculate the distance in cm*/
	distance_cm = ((g_timeHigh / 58)+1);

	if (2 == g_edgeCount)
	{
		/*Clear the edges counter to repeat the process*/
		g_edgeCount = 0;
	}

	return distance_cm;
}

/*
 * Description:
 * 1. This is the call back function called by the ICU Driver. Its address
 *    is sent to the Icu_setCallBack function using Ultrasonic_init function.
 * 2. This function is used to calculate the high time (pulse time)
 *    generated by the Ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if (1 == g_edgeCount)
	{
		/*Clear the timer counter register to start measurements from the first
		 * detected rising edge.
		 */
		Icu_clearTimerValue();

		/*Set the ICU to detect the falling edge*/
		Icu_setEdgeDetectionType(FALLING);
	}
	else if (2 == g_edgeCount)
	{
		/*Store the high time value*/
		g_timeHigh = Icu_getInputCaptureValue();

		/*Detect the rising edge*/
		Icu_setEdgeDetectionType(RISING);

		/*Clear the timer counter register to start measurements again*/
		Icu_clearTimerValue();
	}
}


