/*
 * DIO_PROTO_TYPES.h
 *
 * Created: 11-Nov-23 2:19:31 PM
 *  Author: JOE
 */ 


#ifndef DIO_PROTO_TYPES_H_
#define DIO_PROTO_TYPES_H_

#include "DIO_CONFIG.h"

void DIO_SET_PIN_DIREC (DIO_PORT_ID PORT , DIO_PIN_ID PIN  , DIO_DIRECTION DIRECTION);

void DIO_SET_PIN_VALUE (DIO_PORT_ID PORT , DIO_PIN_ID PIN , DIO_LEVEL VALUE);

void DIO_SET_PORT_DIREC (DIO_PORT_ID PORT,  DIO_DIRECTION DIRECTION);

void DIO_SET_PORT_VALUE (DIO_PORT_ID PORT, uint8 VALUE);

void DIO_TOOGLE_PIN (DIO_PORT_ID PORT, DIO_PIN_ID PIN);

DIO_LEVEL DIO_READ_PIN (DIO_PORT_ID PORT, DIO_PIN_ID PIN );

uint8  DIO_READ_PORT     (DIO_PORT_ID PORT );

void DIO_SET_PULL_UP_RES (DIO_PORT_ID PORT, DIO_PIN_ID PIN);





#endif /* DIO_PROTO_TYPES_H_ */