/*
 * ultrasonic_Interface.h
 *
 *  Created on: Nov 11, 2023
 *      Author: DeLL
 */

#ifndef HAL_ULTRASONIC_ULTRASONIC_PROTO_TYPES_H_
#define HAL_ULTRASONIC_ULTRASONIC_PROTO_TYPES_H_

#include "../../../LIB/STD.h"

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*
 * Description : Function to initialize the Ultrasonic Driver.
 * 	1. Initialize the ICU driver as required.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through
 * 	the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description:
 * Send the Trigger Pulse to the Ultrasonic using the GPIO Driver.
 */
void Ultrasonic_Trigger(void);

/*
 * Description:
 * 1. Send the Trigger Pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description:
 * 1. This is the call back function called by the ICU Driver.
 * 2. This function is used to calculate the high time (pulse time)
 *    generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);



#endif /* HAL_ULTRASONIC_ULTRASONIC_PROTO_TYPES_H_ */
